name: Type Coverage and Linting

on:
  push:
    branches:
      - pyright-testing
  pull_request:
    branches:
      - main
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.x' ]

    name: "Type Coverage and Linting @ ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v3
      
      - name: Install poetry
        run: pipx install poetry
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      
      - run: poetry install
      
      - run: |
          source $(poetry env info --path)/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - run: python -c 'import sys, json; json.dump(sys.path, sys.stdout, indent=4)'
      
      - uses: jakebailey/pyright-action@v1
        with:
          verify-types: "hondana"
          ignore-external: true
